org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=26.3
minecraft_version_compatible=~26.3
loader_version=0.19.5
loader_compatible=>=0.19.5
loom_version=1.17-SNAPSHOT
java_version=25
java_compatible=>=25

# Dependencies
fabric_api_version=0.162.0+26.3
fabric_api_compatible=>=0.162.0+26.3
modmenu_version=21.0.0
