org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=26.2
minecraft_version_compatible=~26.2
loader_version=0.19.3
loader_compatible=>=0.19.3
loom_version=1.17-SNAPSHOT
java_version=25
java_compatible=>=25

# Dependencies
fabric_api_version=0.158.0+26.2
fabric_api_compatible=>=0.158.0+26.2
modmenu_version=20.0.1
